name: GitHub Actions Demo

run-name: Deploy serverless 🚀

on:
  pull_request:
    branches: [ "main" ]

jobs:
  serverless:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i pnpm @vercel/ncc serverless -g && pnpm install --frozen-lockfile
    - run: pnpm run sls:build

    - name: deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage prod --param=bucket_name=${{ env.S3_BUCKET_NAME }}
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ env.S3_BUCKET_NAME }}
