name: NestJS Serverless

run-name: Deploy serverless 🚀

on:
  pull_request:
    branches: [ "main" ]

jobs:
  serverless:
    name: Serverless lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare
      run: |
        npm i pnpm @vercel/ncc serverless -g
        pnpm install --frozen-lockfile

    - name: Build
      run: pnpm run sls:build

    - name: Deploy
      run: |
        export AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
        pnpm run sls:deploy:prod
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
        AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
        AWS_S3_BUCKET: $AWS_S3_BUCKET
        UPLOAD_RATE_TTL: ${{ secrets.UPLOAD_RATE_TTL }}
        UPLOAD_RATE_LIMIT: ${{ secrets.UPLOAD_RATE_LIMIT }}
